bark:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    description: "bark 1"
    webhook: "https://api.day.app/qr3XSFqvNxxxxxxx/{{data}}"
    sound: "minuet"

chanify:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    webhook: "https://api.chanify.net/v1/sender/CIDt-ZgGEiJBQTZaVDIySkxxxxxxx"
    text: "Hello from notify. {{data}}"

dingtalk:
  - notifyLevel: 2
    notifyFormatter: ["{{data}}"]
    token: "5ff195509f5653f6bfffxxxxxxx"
    content: "Hello from notify. {{data}}"

  - notifyLevel: 2
    token: "eb1f45d559a1cea076xxxxxxx"
    secret: "SECabd4d4e56d8899xxxxxxx"
    messageType: "feedCard"
    links: [
      {
        "title":"test",
        "messageURL":"test",
        "picURL":"test"
      }
    ]

discord:
  - notifyLevel: 2
    notifyFormatter: ["{{data}}"]
    webhook: "https://discord.com/api/webhooks/985040095xxxxxxx/uqTQQuwxxxxxxx-xxxxxxx"
    content: "Hello from notify. {{data}}"

googlechat:
  - notifyLevel: 2
    notifyFormatter: ["{{data}}"]
    webhook: "https://chat.googleapis.com/v1/spaces/AAAAxxxxxxx/messages?key=AIzaSyDdI0xxxxxxx&token=BBSS0tJT_7BVGSxxxxxxx"
    text: "Hello from notify. {{data}}"

mailgun:
  - notifyLevel: 3
    notifyFormatter: ["{{data}}, {{data2}}"]
    webhook: "https://api.mailgun.net/v3/sandbox7a9b01aeede542f98635a5fdfa9fbac1.mailgun.org/messages"
    apiKey: "3393aa7e232d9xxxxxxx"
    from: "Mailgun Sandbox <postmaster@sandbox7a9b01aeede542f98635a5fdfa9fbac1.mailgun.org>"
    to: "Ss <xxxxxxx@krunsea.com>"
    subject: "title {{data}}"
    text: "Hello from notify. {{data2}}"

rocketchat:
  - notifyLevel: 2
    notifyFormatter: ["{{data}}"]
    webhook: "http://127.0.0.1:3000/hooks/62a6f649axxxxxxx/SdWX8fXKEs8xMBFxxxxxxx"
    text: "Hello from notify. {{data}}"

telegram:
  - notifyLevel: 2
    notifyFormatter: ["{{data}}"]
    webhook: "https://api.telegram.org/bot516xxxxxxx/sendMessage"
    chatId: "69xxxxxxx"
    text: "Hello from notify. {{data}}"

webhook:
  - notifyLevel: 2
    notifyFormatter: [ "{{data}}" ]
    webhook: "https://httpbin.org/post"
    params:
      k1: "v1"
      k2: "v2"
    data:
      k3: "v3"
    json:
      k4: "v4"

pushover:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    token: "aefgdwtxs1xoxjxxxxxxx"
    user: "uacn4m8sq3cm7jxxxxxxx"
    message: "Hello from notify. {{data}}"

pushbullet:
 - notifyLevel: 1
   notifyFormatter: ["{{data}}"]
   token: "o.crqLtgqLqdM0edqYs1xxxxxxx"
   type: "note"
   body: "Hello from notify. {{data}}"

pushdeer:
 - notifyLevel: 1
   notifyFormatter: ["{{data}}"]
   pushKey: "PDU12208TFNJw3weI89xGxxxxxxx"
   text: "Hello from notify. {{data}}"

ftqq:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    webhook: "https://sctapi.ftqq.com/SCT140140Txxxxxxx.send"
    title: ""
    desp: "Hello from notify. {{data}}"

qpush:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    name: "xxxxxxx"
    code: "xxxxxxx"
    msg: "Hello from notify. {{data}}"

xz:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    webhook: "https://xizhi.qqoq.net/XZf282c9538b8axxxxxxx.send"
    title: "test"
    content: "Hello from notify. {{data}}"

igot:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    webhook: "https://push.hellyw.com/62aacbd09f3cfxxxxxxx"
    title: "test"
    content: "Hello from notify. {{data}}"

zulip:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    webhook: "https://xxxxxxx.zulipchat.com/api/v1/messages"
    botEmail: "test-bot@xxxxxxx.zulipchat.com"
    botKey: "iSaTzykqgY0xxxxxxx"
    type: "stream"
    topic: "test"
    to: "general"
    content: "Hello from notify. {{data}}"

feishu:
  - notifyLevel: 1
    notifyFormatter: ["{{data}}"]
    webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/f9fb75ca-4xxxxxxx"
    msgType: "text"
    secret: "D9kRykxjZgxxxxxxxxxxxxxx"
    content: {"text":"Hello from notify. {{data}}"}